import type { PartDefinition } from '../vehicle/PartDefinition';
import { sideNodes, stackNodes } from '../vehicle/PartDefinition';

/**
 * The part catalog. All sizes are in grid cells (0.5 m each); all masses in kg,
 * thrust in newtons, Isp in seconds. Stats are gameplay-tuned for the 1:10 world.
 *
 * Fuel tanks are procedural since Phase 2: one definition, per-instance
 * integer dimensions (see vehicle/ProceduralPart.ts). The old fixed tanks are
 * kept as `legacy` so v1 saved designs still load, but they are hidden from
 * the palette.
 */
export const PART_DEFINITIONS: PartDefinition[] = [
  {
    id: 'pod-mk1',
    name: 'Capsule Mk1',
    category: 'pod',
    widthCells: 2,
    heightCells: 2,
    dryMass: 300,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.25,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 2),
    stageable: false,
    reactionWheelNm: 15_000,
    cost: 600,
    color: 0xd8dee9,
    // Future habitation data — declared but not simulated yet
    // (see future/HabitationSystem.ts).
    crewCapacity: 1,
    habitableVolume: 2,
    habitationRole: 'command',
  },
  {
    id: 'procedural-fuel-tank',
    name: 'Procedural Fuel Tank',
    category: 'tank',
    // Defaults used when no per-instance dimensions are given.
    widthCells: 2,
    heightCells: 4,
    dryMass: 300, // fallback only; real values derive from procedural config
    fuelCapacity: 2400,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 4),
    stageable: false,
    color: 0xe08a35,
    procedural: {
      minWidthCells: 2,
      maxWidthCells: 4,
      widthStepCells: 2, // even widths only — keeps stack nodes on grid vertices
      minHeightCells: 1,
      maxHeightCells: 16,
      fuelPerCellKg: 300,
      dryMassPerCellKg: 37.5,
      frontalAreaPerWidthCell: 0.4,
      costPerCell: 45,
    },
  },
  {
    // Procedural engine plate: a structural base with one engine mount node
    // every 2 cells of width — symmetric engine clusters (1..4 mounts).
    // Fuel flows through it (fuel groups only cut at decouplers).
    id: 'engine-plate',
    name: 'Engine Plate',
    category: 'structural',
    widthCells: 4,
    heightCells: 1,
    dryMass: 100,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 1.6,
    attachmentNodes: [], // generated procedurally (nodeLayout: enginePlate)
    stageable: false,
    color: 0x7a8494,
    procedural: {
      minWidthCells: 2,
      maxWidthCells: 8,
      widthStepCells: 2,
      minHeightCells: 1,
      maxHeightCells: 1,
      fuelPerCellKg: 0,
      dryMassPerCellKg: 25,
      frontalAreaPerWidthCell: 0.4,
      costPerCell: 60,
      nodeLayout: 'enginePlate',
    },
  },
  {
    id: 'engine-mule',
    name: 'Launch Engine "Mule"',
    category: 'engine',
    widthCells: 2,
    heightCells: 2,
    dryMass: 450,
    fuelCapacity: 0,
    thrustSeaLevel: 95_000,
    thrustVacuum: 108_000,
    ispSeaLevel: 265,
    ispVacuum: 300,
    dragCoefficient: 0.6,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 2),
    stageable: false,
    gimbalRangeDeg: 3,
    cost: 1200,
    color: 0x8d97a3,
  },
  {
    id: 'engine-wisp',
    name: 'Vacuum Engine "Wisp"',
    category: 'engine',
    widthCells: 2,
    heightCells: 2,
    dryMass: 90,
    fuelCapacity: 0,
    thrustSeaLevel: 12_000,
    thrustVacuum: 26_000,
    ispSeaLevel: 140,
    ispVacuum: 330,
    dragCoefficient: 0.6,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 2),
    stageable: false,
    gimbalRangeDeg: 4,
    cost: 900,
    color: 0xa8b6c8,
  },
  {
    id: 'procedural-decoupler',
    name: 'Procedural Decoupler',
    category: 'decoupler',
    widthCells: 2,
    heightCells: 1,
    dryMass: 40,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.8,
    attachmentNodes: [],
    stageable: true,
    cost: 150,
    color: 0xf2d24b,
    procedural: {
      minWidthCells: 2,
      maxWidthCells: 6,
      widthStepCells: 2,
      minHeightCells: 1,
      maxHeightCells: 4,
      fuelPerCellKg: 0,
      dryMassPerCellKg: 20,
      frontalAreaPerWidthCell: 0.4,
      costPerCell: 75,
      nodeLayout: 'stack',
    },
  },
  {
    id: 'decoupler-1',
    name: 'Decoupler (legacy)',
    category: 'decoupler',
    widthCells: 2,
    heightCells: 1,
    dryMass: 40,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 1),
    stageable: true,
    cost: 150,
    color: 0xf2d24b,
    legacy: true,
  },
  {
    // Radial decoupler: sits between a core tank's flank and a booster
    // tank's flank (left node <-> right node). Fires with its assigned stage
    // and leaves WITH the booster it releases.
    id: 'radial-decoupler',
    name: 'Radial Decoupler',
    category: 'decoupler',
    widthCells: 1,
    heightCells: 2,
    dryMass: 50,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.4,
    attachmentNodes: [
      { xCells: 0, yCells: 1, kind: 'left' },
      { xCells: 1, yCells: 1, kind: 'right' },
    ],
    stageable: true,
    cost: 180,
    color: 0xc9a13a,
  },
  {
    // Aerodynamic cap for booster columns. Bottom node only.
    id: 'nose-cone',
    name: 'Nose Cone',
    category: 'nose',
    widthCells: 2,
    heightCells: 2,
    dryMass: 60,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.15,
    frontalArea: 0.8,
    attachmentNodes: [{ xCells: 1, yCells: 0, kind: 'bottom' }],
    stageable: false,
    cost: 120,
    color: 0xb8c2cf,
  },
  // ---------------------------------------------------------------------
  // The parts below are placeable but functionally inert in the MVP.
  // ---------------------------------------------------------------------
  {
    // Procedural parachute (RealChute-style): right-click in the VAB to set
    // type/diameter/material/deploy altitude. Mass & cost derive from the
    // canopy (vehicle/ProceduralPart.resolveChute); deployment physics in
    // vehicle/RocketRuntime.stepChutes.
    id: 'parachute-1',
    name: 'Parachute',
    category: 'parachute',
    widthCells: 1,
    heightCells: 1,
    dryMass: 50,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.3,
    frontalArea: 0.25,
    // Center bottom node: aligns with a pod's top node on the tapered 1×1 crown.
    attachmentNodes: [{ xCells: 0.5, yCells: 0, kind: 'bottom' }],
    stageable: true,
    cost: 200,
    color: 0xd05a5a,
  },
  {
    // LT-2-style radial landing strut: one leg per part; mirror in the VAB for pairs.
    // Stowed along the hull; deploy rotates out + extends hydraulically (see LandingLegs.ts).
    id: 'legs-1',
    name: 'Landing Strut',
    category: 'legs',
    widthCells: 1,
    heightCells: 3,
    dryMass: 55,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.45,
    frontalArea: 0.22,
    attachmentNodes: sideNodes(1, 3),
    stageable: false,
    cost: 150,
    color: 0x8a7f6d,
  },
  {
    // Functional since the thermal model landed: its high maxTempK lets it
    // soak reentry flux that would destroy anything else (mount it at the
    // bottom and enter retrograde). TODO: ablation (mass loss while hot).
    id: 'heatshield-1',
    name: 'Heat Shield',
    category: 'heatshield',
    widthCells: 2,
    heightCells: 1,
    dryMass: 120,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.4,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 1),
    stageable: false,
    cost: 300,
    color: 0x6b4f3a,
  },
  {
    // Launch clamp: hangs on a tank flank, pins the vessel to the pad until
    // its stage fires (defaults to stage 1, alongside radial decouplers).
    // The released clamp stays behind on the pad as debris.
    id: 'launch-clamp',
    name: 'Launch Clamp',
    category: 'clamp',
    widthCells: 1,
    heightCells: 4,
    dryMass: 200,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.8,
    frontalArea: 0.4,
    attachmentNodes: [
      { xCells: 0, yCells: 3, kind: 'left' },
      { xCells: 1, yCells: 3, kind: 'right' },
    ],
    stageable: true,
    cost: 250,
    color: 0x5f6d7d,
  },
  {
    // First electricity storage (systems/Resources migration, phase 6).
    id: 'battery-1',
    name: 'Battery Pack',
    category: 'utility',
    widthCells: 0.5,
    heightCells: 2,
    dryMass: 45,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.2,
    attachmentNodes: sideNodes(0.5, 2),
    stageable: false,
    cost: 350,
    electricCapacity: 300,
    color: 0x3f7c5a,
  },
  {
    // Fixed solar panel: trickle charge in sunlight (eclipse-aware).
    // TODO: deployable panels, sun-tracking, breakage under q.
    id: 'solar-1',
    name: 'Solar Panel',
    category: 'utility',
    widthCells: 0.25,
    heightCells: 1,
    dryMass: 35,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.6,
    frontalArea: 0.1,
    attachmentNodes: sideNodes(0.25, 1),
    stageable: false,
    cost: 500,
    electricGenPerSec: 1.2,
    color: 0x27476e,
  },
  {
    // Probe core: uncrewed control. Drains electricity; when the battery is
    // flat, reaction wheels die (gimbal still steers a burning engine).
    id: 'probe-1',
    name: 'Probe Core',
    category: 'pod',
    widthCells: 2,
    heightCells: 1,
    dryMass: 80,
    fuelCapacity: 0,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.3,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 1),
    stageable: false,
    reactionWheelNm: 4_000,
    cost: 800,
    electricCapacity: 60,
    electricDrainPerSec: 0.06,
    color: 0xc0a35e,
  },
  // ---------------------------------------------------------------------
  // Legacy fixed tanks: hidden from the palette, kept so v1 saves load.
  // ---------------------------------------------------------------------
  {
    id: 'tank-s',
    name: 'Fuel Tank S (legacy)',
    category: 'tank',
    widthCells: 2,
    heightCells: 2,
    dryMass: 100,
    fuelCapacity: 700,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 2),
    stageable: false,
    cost: 250,
    color: 0xe8913a,
    legacy: true,
  },
  {
    id: 'tank-m',
    name: 'Fuel Tank M (legacy)',
    category: 'tank',
    widthCells: 2,
    heightCells: 4,
    dryMass: 300,
    fuelCapacity: 2400,
    thrustSeaLevel: 0,
    thrustVacuum: 0,
    ispSeaLevel: 0,
    ispVacuum: 0,
    dragCoefficient: 0.5,
    frontalArea: 0.8,
    attachmentNodes: stackNodes(2, 4),
    stageable: false,
    cost: 500,
    color: 0xd97b2f,
    legacy: true,
  },
];

/** Fast id -> definition lookup used everywhere a defId must be resolved. */
export function createPartCatalog(): Map<string, PartDefinition> {
  return new Map(PART_DEFINITIONS.map((def) => [def.id, def]));
}

/** Parts shown in the builder palette (legacy definitions are hidden). */
export function paletteParts(): PartDefinition[] {
  return PART_DEFINITIONS.filter((def) => !def.legacy);
}
